### ISSUE TITLE
Add support for TZ variable

### ISSUE THREAD

**Issue by onedr0p** [whi-tw/docker-xteve#2]
First off thanks for the image! It would be nice to customize the timezone with a `TZ` environment variable.

**Comment by whi-tw** [comment]
Hi, I've just tested this out, and can't see any problem with using `TZ` as an environment variable as-is:

```
/xteve # date
Mon Jul  6 08:28:48 UTC 2020
/xteve # export TZ=Europe/Paris
/xteve # date
Mon Jul  6 10:29:00 CEST 2020
```

Is there something I'm missing?

**Comment by onedr0p** [comment]
Oh nice! sorry I didn't see this documented, maybe add it to the README?
