### ISSUE TITLE
Multi-arch

### ISSUE THREAD

**Issue by onedr0p** [whi-tw/docker-xteve#3]
Please add support for multi-arch docker images (arm64 and arm)
Thanks!

**Comment by whi-tw** [comment]
@onedr0p - should be sorted now, maybe? https://hub.docker.com/layers/tnwhitwell/xteve/latest/images/sha256-ca22512deeca7973ccae30999372b6d239afd56d61f5d2a3a03d73e2f0eb2e0b?context=explore

**Comment by onedr0p** [comment]
The docker image appears to be multi-arch but I believe you need to build xteve from source in your CI and pass the right GOARCH flags for compilation.

https://github.com/whi-tw/docker-xteve/blob/master/ci/pipelines/build-docker-image.yml#L94

**Comment by onedr0p** [comment]
For example, here is a project I do this for:
https://github.com/onedr0p/exportarr/blob/master/.github/workflows/main.yml

and the relating Dockerfile:
https://github.com/onedr0p/exportarr/blob/master/build/package/Dockerfile

**Comment by whi-tw** [comment]
I just thought about this while eating lunch. Turns out I need to do one more thing. Doh. Give me a couple hours.

**Comment by whi-tw** [comment]
@onedr0p: I didn't see you had replied!

Happily now building from source, and tested with qemu - seems to be working A-OK

**Comment by onedr0p** [comment]
Great, thanks!
